name: Gradle Check
on:
  push:
  pull_request:
jobs:
  gradle-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Running Tests
        run: ./gradlew check jacocoTestReport --info --no-daemon --stacktrace
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
